Update pull-100-docker-images.yml

diff --git a/.github/workflows/pull-100-docker-images.yml b/.github/workflows/pull-100-docker-images.yml
--- a/.github/workflows/pull-100-docker-images.yml
+++ b/.github/workflows/pull-100-docker-images.yml
@@ -149,12 +149,13 @@ jobs:
           )
 
           for image in "${images[@]}"; do
-            echo "::group::Pulling $image"
-            if ! docker image inspect "$image" > /dev/null 2>&1; then
-              .github/retry.sh 5 2 docker pull "$image" || true
-            else
-              echo "Image already present"
-            fi
+            docker pull "$image" || true
+            #echo "::group::Pulling $image"
+            #if ! docker image inspect "$image" > /dev/null 2>&1; then
+            #  .github/retry.sh 5 2 docker pull "$image" || true
+            #else
+            #  echo "Image already present"
+            #fi
             echo "::endgroup::"
           done
 
